# Generated by Django 5.1.4 on 2024-12-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
    ]
