# Generated by Django 5.1.4 on 2024-12-09 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_cursoscomprados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cursoscomprados',
            index=models.Index(fields=['-curso_comprado', '-usuario'], name='cursos_curs_curso_c_2a8caa_idx'),
        ),
    ]
