# Generated by Django 5.1.4 on 2024-12-13 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alter_curso_created_alter_curso_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 20, 51, 11, 430975, tzinfo=datetime.timezone.utc)),
        ),
    ]
