# Generated by Django 5.1.4 on 2024-12-13 21:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_curso_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.category'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 21, 0, 14, 831406, tzinfo=datetime.timezone.utc)),
        ),
    ]
