# Generated by Django 5.1.4 on 2024-12-14 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_alter_curso_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 14, 21, 55, 14, 201524, tzinfo=datetime.timezone.utc)),
        ),
    ]
