# Generated by Django 5.1.4 on 2024-12-14 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_alter_curso_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 14, 23, 40, 44, 815729, tzinfo=datetime.timezone.utc)),
        ),
    ]
