# Generated by Django 5.1.4 on 2024-12-15 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_alter_curso_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 0, 32, 13, 360270, tzinfo=datetime.timezone.utc)),
        ),
    ]
